version: '3.7'

services:
    mongo-express:
        image: mongo-express
        depends_on:
            - mongodb
        restart: unless-stopped
        expose:
            - 8081
        environment:
            VIRTUAL_HOST: ${MONGO_EXPRESS_VIRTUAL_HOST}
            VIRTUAL_PORT: 8081
            ME_CONFIG_MONGODB_SERVER: "mongodb.compose"
            #ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
            #ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGODB_ROOT_PASSWORD}"
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_AUTH_USER}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_AUTH_PASS}
        networks:
            default:
                aliases:
                    - mongo-express.compose
            nginx-proxy: ~

networks:
    nginx-proxy:
        external: true

