version: '3.7'

services:
    mongodb:
        image: 'mongo'
        restart: always
        labels:
            kompose.service.type: nodeport
        expose:
            - 27017
        volumes:
            - ../volumes/mongodb:/data/db
        networks:
            default:
                aliases:
                    - mongodb.compose
                    - mongo
            application-network:
                aliases:
                    - "${MONGODB_APN_HOSTNAME}"

networks:
    application-network:
        external: true

